version: "3.8"

networks:
    devopsnetwork:
        driver: bridge
        name: devopsnetwork

services:
    mainapp:
        container_name: devopsapp
        build: 
            context: ./../
            dockerfile: Dockerfile
        image: devopsapp
        networks:
            devopsnetwork:
                aliases: 
                    - mainapp
        ports:
        - "5000:8080"
        expose:
            - "5000"
        environment:
            APP_INSTANCE: 
            APP_PORT: 8080
            APP_HOST: "0.0.0.0"